ln -sf ../model/WRFV3/test/em_real/CAM_ABS_DATA  ./
ln -sf ../model/WRFV3/test/em_real/CAM_AEROPT_DATA  ./
ln -sf ../model/WRFV3/test/em_real/ETAMPNEW_DATA  ./
ln -sf ../model/WRFV3/test/em_real/ETAMPNEW_DATA_DBL  ./
ln -sf ../model/WRFV3/test/em_real/GENPARM.TBL  ./
ln -sf ../model/WRFV3/test/em_real/grib2map.tbl  ./
ln -sf ../model/WRFV3/test/em_real/gribmap.txt  ./
ln -sf ../model/WRFV3/test/em_real/LANDUSE.TBL  ./
ln -sf ../model/WRFV3/test/em_real/ndown.exe  ./
ln -sf ../model/WRFV3/test/em_real/real.exe  ./
ln -sf ../model/WRFV3/test/em_real/RRTM_DATA  ./
ln -sf ../model/WRFV3/test/em_real/RRTM_DATA_DBL  ./
ln -sf ../model/WRFV3/test/em_real/RRTMG_LW_DATA  ./
ln -sf ../model/WRFV3/test/em_real/RRTMG_LW_DATA_DBL  ./
ln -sf ../model/WRFV3/test/em_real/RRTMG_SW_DATA  ./
ln -sf ../model/WRFV3/test/em_real/RRTMG_SW_DATA_DBL  ./
ln -sf ../model/WRFV3/test/em_real/SOILPARM.TBL  ./
ln -sf ../model/WRFV3/test/em_real/URBPARM.TBL  ./
ln -sf ../model/WRFV3/test/em_real/VEGPARM.TBL  ./
ln -sf ../model/WRFV3/test/em_real/wrf.exe  ./
