ln -sf ../model/WRFV3/run/CAM_ABS_DATA  ./
ln -sf ../model/WRFV3/run/CAM_AEROPT_DATA  ./
ln -sf ../model/WRFV3/run/ETAMPNEW_DATA  ./
ln -sf ../model/WRFV3/run/ETAMPNEW_DATA_DBL  ./
ln -sf ../model/WRFV3/run/GENPARM.TBL  ./
ln -sf ../model/WRFV3/run/grib2map.tbl  ./
ln -sf ../model/WRFV3/run/gribmap.txt  ./
ln -sf ../model/WRFV3/run/LANDUSE.TBL  ./
ln -sf ../model/WRFV3/run/ndown.exe  ./
ln -sf ../model/WRFV3/run/real.exe  ./
ln -sf ../model/WRFV3/run/RRTM_DATA  ./
ln -sf ../model/WRFV3/run/RRTM_DATA_DBL  ./
ln -sf ../model/WRFV3/run/RRTMG_LW_DATA  ./
ln -sf ../model/WRFV3/run/RRTMG_LW_DATA_DBL  ./
ln -sf ../model/WRFV3/run/RRTMG_SW_DATA  ./
ln -sf ../model/WRFV3/run/RRTMG_SW_DATA_DBL  ./
ln -sf ../model/WRFV3/run/SOILPARM.TBL  ./
ln -sf ../model/WRFV3/run/URBPARM.TBL  ./
ln -sf ../model/WRFV3/run/VEGPARM.TBL  ./
ln -sf ../model/WRFV3/run/wrf.exe  ./
